services:
  front:
    build: ./final_pjt_front
    volumes:
      - ./final_pjt_front:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - back
  back:
    build: ./final_pjt_back
    volumes:
      - ./final_pjt_back:/usr/src/app
    ports:
      - "8000:8000"
