# Generated by Django 4.2.8 on 2024-05-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField(unique=True)),
                ('ttb', models.FloatField()),
                ('tts', models.FloatField()),
                ('cur_nm', models.TextField()),
            ],
        ),
    ]
