# Generated by Django 4.2.8 on 2024-05-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_name', models.CharField(default='', max_length=30, unique=True)),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('nickname', models.CharField(default='', max_length=30, unique=True)),
                ('birth', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('main_bank', models.CharField(blank=True, max_length=30, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('asset', models.IntegerField(blank=True, null=True)),
                ('desired_asset', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
